### ISSUE TITLE
[Feature Request] Renaming inputs

### ISSUE THREAD

**Issue by lukasmalkmus** [SeydX/homebridge-bravia-tvos#115]
It is possible to rename inputs of TVs in HomeKit. It would be awesome to preserve these changes across restarts. If that isn't possible, it would be awesome to map Display Names in the config.

**Comment by SeydX** [comment]
@lukasmalkmus 

It is possible to change the names atm, but it will revert back after restart because the plugin exposes the tv as a external device. And external devices will not be cached as bridged devices.

Therefore i need to add a own cache function to allow this. I thing i will add this function for the next version

**Comment by SeydX** [comment]
Added in v4.1.8
