### ISSUE TITLE
Different config UIs

### ISSUE THREAD

**Issue by lukasmalkmus** [SeydX/homebridge-bravia-tvos#169]
I noticed the following issues with the Config UI:

1. As seen in the first part of the video, when navigating to `Configs` and then selecting the channels or inputs of my only configured TV, only the first entry shows up. When clicking "Add Input/Channel", the next entry that is present in `config.json` is revealed.

2. When selecting my configured TV from the list and clicking the button to edit that config, the `Channels` list is loaded completely, but has a different layout as in the first part of the video.

https://user-images.githubusercontent.com/9931588/135852993-b8a893d6-edc9-48e3-bf3f-363626137193.mov

**Comment by SeydX** [comment]
Hey @lukasmalkmus 

1. its because you use the „advanced static config schema“ which can not be handled through config ui x very well due to the nested arrays. 
2. The layout is different because u are using the „advanced static config schema“. This all is intended and not a issue by the plugin

Use this form of config if you can handle the „advanced“ configuration. Its only for peoply with the required knowledge what want to add „other“ inputs which can not be cached through the plugin

Why u dont use the „edit icon“ to edit your configuration? Because the above „Configs“ navi IS NOT THE SAME as the edit button

**Comment by lukasmalkmus** [comment]
Alright, got it.
